# src/storage/interfaces.py
from __future__ import annotations
from typing import Protocol, List
from src.shared.schema import Question, RoutedQuestion, Plan, RawAnswer, VerifiedAnswer

class RunRepositoryP1(Protocol):
    # lifecycle
    def init(self) -> None: ...
    def upsert_run(self, run_id: str, paper_path: str) -> None: ...

    # P1
    def save_questions(self, run_id: str, questions: List[Question]) -> None: ...
    def load_questions(self, run_id: str) -> List[Question]: ...

    # (add gradually as phases arrive)
    # def save_routes(self, run_id: str, routes: List[RoutedQuestion]) -> None: ...
    # def load_routes(self, run_id: str) -> List[RoutedQuestion]: ...
    
    # def save_plans(self, run_id: str, plans: List[Plan]) -> None: ...
    # def load_plans(self, run_id: str) -> List[Plan]: ...
    
    # def save_raw_answers(self, run_id: str, answers: List[RawAnswer]) -> None: ...
    # def load_raw_answers(self, run_id: str) -> List[RawAnswer]: ...
    
    # def save_verified(self, run_id: str, verified: List[VerifiedAnswer]) -> None: ...
    # def load_verified(self, run_id: str) -> List[VerifiedAnswer]: ...